import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar"
import AppSidebar from "@/components/app-sidebar"
import Header from "./Header/page";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>

          <AppSidebar />
          <SidebarInset className="flex my-2 ">
            <div className="flex">
              <SidebarTrigger className="absolute z-20" />
              <Header className="relative" />
            </div>


            <main className="flex-1 p-6 overflow-auto">
              {children}
            </main>
          </SidebarInset>

        </SidebarProvider>



      </body>

    </html >
  );
}
